In [1]:
from histimator.models import HistiModel, HistiChannel, HistiSample
from histimator.estimator import BinnedLH

In [2]:
from scipy.optimize import minimize
import numpy as np
%matplotlib inline

## Testing multiple Regions

In [3]:
hist_1 = np.asarray([1,2,3,4])
hist_2 = np.asarray([5,5,5,5])
hist_3 = np.asarray([3,4,5,4])
bins_1 = np.asarray([0,1,2,3,4])
bins_2 = np.asarray([0,1,2])
bins_3 = np.asarray([0,1,2,3,4,5,6,7,8])

In [4]:
m = HistiModel('model')
signal_1 = HistiSample('signal')
signal_1.SetHisto((hist_1,bins_1))
signal_1.AddNorm("SigXSecOverSM",1.0,0,3)
background_1 = HistiSample('background1')
background_1.SetHisto((hist_2,bins_1))
background_1.AddOverallSys("BackgroundNormSyst1",0.9,1.1)
background_2 = HistiSample('background1')
background_2.SetHisto((hist_3,bins_1))
background_2.AddOverallSys("BackgroundNormSyst2",0.7,1.3)

In [5]:
chan1 = HistiChannel("SR")
chan1.AddSample(signal_1)
chan1.AddSample(background_1)
chan1.AddSample(background_2)

In [6]:
data1 = hist_1*2 +hist_2 +hist_3

chan1.SetData(data1)
m.AddChannel(chan1)

In [7]:
m.pdf

<histimator.pdfs.HistiAddPdf instance at 0x108ec05f0>

In [8]:
blh = BinnedLH(m, minimiser='scipy')
params = m.Parameters('scipy')
print params
minimiser = minimize(blh, params, method='bfgs')
print minimiser.x

[1.0, 0.60000000000000009, 0.20000000000000007]
[  1.99999824e+00   3.65847652e-06   1.91385133e-06]


In [9]:
signal_1 = HistiSample('signal')
signal_1.SetHisto((hist_1[:2],bins_2))
signal_1.AddNorm("SigXSecOverSM",1.0,0,3)
background_1 = HistiSample('background1')
background_1.SetHisto((hist_2[:2],bins_2))
background_1.AddOverallSys("BackgroundNormSyst1",0.9,1.1)
background_2 = HistiSample('background1')
background_2.SetHisto((hist_3[:2],bins_2))
background_2.AddOverallSys("BackgroundNormSyst3",0.7,1.3)

In [10]:
chan2 = HistiChannel("CR1")
chan2.AddSample(signal_1)
chan2.AddSample(background_1)
chan2.AddSample(background_2)

In [11]:
data2 = hist_1[:2]*2 +hist_2[:2] +hist_3[:2]

chan2.SetData(data2)
m.AddChannel(chan2)

In [12]:
blh = BinnedLH(m, minimiser='scipy')
params = m.Parameters('scipy')
print params
minimiser = minimize(blh, params, method='bfgs')
print minimiser.x

[1.0, 0.60000000000000009, 0.60000000000000009, 0.20000000000000007]
[  2.00002581e+00   2.63602508e-04  -1.32532944e-04   2.00000000e-01]


In [13]:
signal_1 = HistiSample('signal')
signal_1.SetHisto((np.hstack([hist_1,np.flip(hist_1,0)]),bins_3))
signal_1.AddNorm("SigXSecOverSM",1.0,0,3)
background_1 = HistiSample('background1')
background_1.SetHisto((np.hstack([hist_2,hist_2]),bins_3))
background_1.AddOverallSys("BackgroundNormSyst1",0.9,1.1)
background_2 = HistiSample('background1')
background_2.SetHisto((np.hstack([hist_3,hist_3]),bins_3))
background_2.AddOverallSys("BackgroundNormSyst2",0.7,1.3)

In [14]:
chan3 = HistiChannel("CR2")
chan3.AddSample(signal_1)
chan3.AddSample(background_1)
chan3.AddSample(background_2)

In [15]:
data3 = np.hstack([hist_1,np.flip(hist_1,0)])*2 + np.hstack([hist_2,hist_2]) + np.hstack([hist_3,hist_3])

chan3.SetData(data3)
m.AddChannel(chan3)

In [16]:
blh = BinnedLH(m, minimiser='scipy')
params = m.Parameters('scipy')
print params
minimiser = minimize(blh, params, method='bfgs')
print minimiser.x

[1.0, 0.60000000000000009, 0.60000000000000009, 0.20000000000000007]
[  2.00000244e+00  -3.62549878e-05   1.57895349e-05   2.00000000e-01]


# Testing big models

In [17]:
hist_1 = np.linspace(1,100,100)
hist_2 = np.ones(100)*50
hist_3 = np.ones(100)*25
bins_1 = np.linspace(0,100,101)
bins_2 = np.linspace(0,50,51)
bins_3 = np.asarray([0,1,2,3,4,5,6,7,8])

In [18]:
m = HistiModel('model')
signal_1 = HistiSample('signal')
signal_1.SetHisto((hist_1,bins_1))
signal_1.AddNorm("SigXSecOverSM",1.0,0,3)
background_1 = HistiSample('background1')
background_1.SetHisto((hist_2,bins_1))
background_1.AddOverallSys("BackgroundNormSyst1",0.9,1.1)
background_2 = HistiSample('background1')
background_2.SetHisto((hist_3,bins_1))
background_2.AddOverallSys("BackgroundNormSyst2",0.7,1.3)
background_3 = HistiSample('background3')
background_3.SetHisto((hist_2,bins_1))
up = hist_2 + hist_1*0.1
down = hist_2 - hist_1*0.1
background_3.AddHistoSys("BackgroundNormSyst3",down,up)

In [19]:
chan1 = HistiChannel("SR")
chan1.AddSample(signal_1)
chan1.AddSample(background_1)
chan1.AddSample(background_2)
chan1.AddSample(background_3)
data1 = hist_1*2 +hist_2*2 +hist_3*2

chan1.SetData(data1)
m.AddChannel(chan1)

In [20]:
blh = BinnedLH(m, minimiser='scipy')
params = m.Parameters('scipy')
print params
minimiser = minimize(blh, params, method='bfgs')
print minimiser.x

[1.0, 0.60000000000000009, 10.1, 0.20000000000000007]
[ 0.55507401  0.55083931  9.19563134  0.15708834]


In [21]:
m = HistiModel('model')
m.AddChannel(chan1)

In [22]:
signal_1 = HistiSample('signal')
signal_1.SetHisto((hist_1[:50],bins_2))
signal_1.AddNorm("SigXSecOverSM",1.0,0,3)
background_1 = HistiSample('background1')
background_1.SetHisto((hist_2[:50]*.1,bins_2))
background_1.AddOverallSys("BackgroundNormSyst1",0.95,1.05)
background_2 = HistiSample('background1')
background_2.SetHisto((hist_3[:50],bins_2))
background_2.AddOverallSys("BackgroundNormSyst2",0.7,1.3)
background_3 = HistiSample('background3')
background_3.SetHisto((hist_2[:50],bins_2))
up = hist_2[:50] + np.flip(hist_1,0)[:50]*0.1
down = hist_2[:50] - np.flip(hist_1,0)[:50]*0.1
background_3.AddHistoSys("BackgroundHistoSyst4",down,up)

In [23]:
chan2 = HistiChannel("CR1")
chan2.AddSample(signal_1)
chan2.AddSample(background_1)
chan2.AddSample(background_2)
#chan2.AddSample(background_3)
data2 = hist_1*.2 +hist_2*2 +hist_3*2

chan2.SetData(data2[:50])
m.AddChannel(chan1)

In [24]:
blh = BinnedLH(m, minimiser='scipy')
params = m.Parameters('scipy')
print params
minimiser = minimize(blh, params, method='bfgs')
print minimiser.x

[1.0, 0.60000000000000009, 10.1, 0.20000000000000007]
[ 0.55507402  0.55083931  9.19563133  0.15708834]
